function quickScaffoldReactTest (componentName) {
  /*
    Assumes a directory structure such that the test folder is in the same folder as the component
    Component Folder
      > Component.jsx
      > __tests__
        > Component.text.jsx -- content generated by this utility
  */
  console.log(`
import React from 'react';
import renderer from 'react-test-renderer';

import ${componentName} from '../${componentName}';

function getComponentJSON(mockProps) {
  const componentJSX = <${componentName} {...mockProps} />;
  return renderer.create(componentJSX).toJSON();
}

describe('${componentName}', () => {
  test('renders all expected components', () => {
    const tree = getComponentJSON();
    expect(tree).toMatchSnapshot();
  });
});
  `);
}
